export const courses = [
  {
    id: "1",
    title: "Complete Web Development Bootcamp",
    provider: "Udemy",
    rating: 4.8,
    reviewCount: 12543,
    description: "Learn web development from scratch. HTML, CSS, JavaScript, React, Node and more!",
    image: "/placeholder.svg?height=400&width=600",
    category: "Programming",
    level: "Beginner",
    price: "$19.99",
  },
  {
    id: "2",
    title: "UI/UX Design Fundamentals",
    provider: "Coursera",
    rating: 4.6,
    reviewCount: 8721,
    description: "Master the principles of user interface and user experience design for digital products.",
    image: "/placeholder.svg?height=400&width=600",
    category: "Design",
    level: "Intermediate",
    price: "$49.99",
  },
  {
    id: "3",
    title: "Data Science and Machine Learning",
    provider: "edX",
    rating: 4.9,
    reviewCount: 5432,
    description: "Comprehensive course on data science, machine learning algorithms and practical applications.",
    image: "/placeholder.svg?height=400&width=600",
    category: "Data Science",
    level: "Advanced",
    price: "$79.99",
  },
  {
    id: "4",
    title: "Digital Marketing Masterclass",
    provider: "Udemy",
    rating: 4.5,
    reviewCount: 7654,
    description: "Learn SEO, social media marketing, email campaigns, and digital advertising strategies.",
    image: "/placeholder.svg?height=400&width=600",
    category: "Marketing",
    level: "Beginner",
    price: "$24.99",
  },
  {
    id: "5",
    title: "Python for Everybody",
    provider: "Coursera",
    rating: 4.7,
    reviewCount: 9876,
    description: "Learn Python programming from the ground up. Perfect for beginners with no coding experience.",
    image: "/placeholder.svg?height=400&width=600",
    category: "Programming",
    level: "Beginner",
    price: "Free",
  },
  {
    id: "6",
    title: "Business Analytics and Intelligence",
    provider: "Pluralsight",
    rating: 4.4,
    reviewCount: 3210,
    description: "Master data analysis techniques to drive business decisions and strategy.",
    image: "/placeholder.svg?height=400&width=600",
    category: "Business",
    level: "Intermediate",
    price: "$59.99",
  },
]
